// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	reportStartupPhase: (phase: StartupPhase) => __TAURI_INVOKE<null>("report_startup_phase", { phase }),
	getStartupPhase: () => __TAURI_INVOKE<StartupPhase>("get_startup_phase"),
	finishStartup: () => __TAURI_INVOKE<null>("finish_startup"),
	listMods: (gameId: number, params: {
	query: string | null,
	limit: number | null,
	sort: string | null,
	category_id: number | null,
	page: number | null,
	ids: number[] | null,
	tags: number[] | null,
	block_tags: number[] | null,
} | null) => __TAURI_INVOKE<ModPage>("list_mods", { gameId, params }),
	getMod: (id: number) => __TAURI_INVOKE<ModDetail>("get_mod", { id }),
	listModFiles: (modId: number) => __TAURI_INVOKE<FilePage>("list_mod_files", { modId }),
	listModLinks: (modId: number) => __TAURI_INVOKE<LinkPage>("list_mod_links", { modId }),
	listCategories: (gameId: number) => __TAURI_INVOKE<unknown>("list_categories", { gameId }),
	nexusSearchMods: (gameId: string, query: string, sort: string, offset: number | null) => __TAURI_INVOKE<ModPage>("nexus_search_mods", { gameId, query, sort, offset }),
	nexusGetModDetail: (gameId: string, modId: number) => __TAURI_INVOKE<ModDetail>("nexus_get_mod_detail", { gameId, modId }),
	nexusListModFiles: (gameId: string, modId: number) => __TAURI_INVOKE<FilePage>("nexus_list_mod_files", { gameId, modId }),
	/**
	 *  Identifies a dropped archive against Nexus before it is installed as an
	 *  unidentified entry. The renderer calls this ahead of install_dropped_file; a
	 *  NotFound or Ambiguous result still falls through to the existing unidentified
	 *  install path, this only ever adds an identity, never blocks one.
	 */
	identifyDroppedArchive: (gameId: string, path: string) => __TAURI_INVOKE<NexusArchiveIdentity>("identify_dropped_archive", { gameId, path }),
	nexusOauthStart: () => __TAURI_INVOKE<void>("nexus_oauth_start"),
	nexusOauthSignedIn: () => __TAURI_INVOKE<boolean>("nexus_oauth_signed_in"),
	nexusOauthSignOut: () => __TAURI_INVOKE<void>("nexus_oauth_sign_out"),
	listTags: (gameId: number) => __TAURI_INVOKE<unknown>("list_tags", { gameId }),
	secretStoreAvailable: () => __TAURI_INVOKE<boolean>("secret_store_available"),
	setDiscordPresenceEnabled: (enabled: boolean) => __TAURI_INVOKE<void>("set_discord_presence_enabled", { enabled }),
	updateDiscordPresence: (game: string) => __TAURI_INVOKE<void>("update_discord_presence", { game }),
	/**
	 *  Returns a backwards-compatible flat view of PD3 settings for the renderer.
	 *  Commit 4 will switch callers to get_game_settings once the game switcher lands.
	 */
	getSettings: () => __TAURI_INVOKE<unknown>("get_settings"),
	getGameSettings: (gameId: string) => __TAURI_INVOKE<GameSettings_Serialize>("get_game_settings", { gameId }),
	setLauncher: (gameId: string, launcher: string) => __TAURI_INVOKE<void>("set_launcher", { gameId, launcher }),
	setLaunchOptions: (gameId: string, launchOptions: string) => __TAURI_INVOKE<void>("set_launch_options", { gameId, launchOptions }),
	setCrimebossInstallMode: (mode: string) => __TAURI_INVOKE<void>("set_crimeboss_install_mode", { mode }),
	setSuppressCrashReporter: (gameId: string, suppress: boolean) => __TAURI_INVOKE<void>("set_suppress_crash_reporter", { gameId, suppress }),
	setSkipFileopenlogWarning: (skip: boolean) => __TAURI_INVOKE<void>("set_skip_fileopenlog_warning", { skip }),
	dismissDepsWarning: (modId: number) => __TAURI_INVOKE<void>("dismiss_deps_warning", { modId }),
	/**
	 *  Counts a successful mod install toward the one-time "star us on GitHub"
	 *  prompt. When the milestone is reached in a clean session, the shown flag is
	 *  persisted *before* the renderer displays anything (write-on-show), so the
	 *  prompt can never fire twice while settings.json survives.
	 */
	recordSuccessfulInstall: (cleanSession: boolean) => __TAURI_INVOKE<void>("record_successful_install", { cleanSession }),
	/**
	 *  Current analytics consent: None = not yet asked, Some(true/false) = chosen.
	 *  The Option only exists at this IPC boundary — settings.json itself tracks
	 *  "asked" and "enabled" as two separate plain bools (see Settings).
	 */
	getAnalyticsConsent: () => __TAURI_INVOKE<boolean | null>("get_analytics_consent"),
	/**
	 *  Records the user's explicit analytics choice. Generates the anonymous install
	 *  ID lazily on first opt-in, so a user who never enables analytics never gets one.
	 */
	setAnalyticsConsent: (enabled: boolean) => __TAURI_INVOKE<void>("set_analytics_consent", { enabled }),
	/**
	 *  Renderer-origin events route through here; Rust-native events call track
	 *  directly. Both share the consent gate in send_event.
	 */
	trackEvent: (name: string, params: unknown | null) => __TAURI_INVOKE<void>("track_event", { name, params }),
	getInstalled: (gameId: string) => __TAURI_INVOKE<InstalledResponse_Serialize>("get_installed", { gameId }),
	installMod: (modId: number, gamePath: string, folderId: string | null, gameId: string) => __TAURI_INVOKE<InstallOutcome_Serialize>("install_mod", { modId, gamePath, folderId, gameId }),
	installFile: (modId: number, modName: string, fileId: number, downloadUrl: string, fileType: string, modVersion: string, gamePath: string, gameId: string) => __TAURI_INVOKE<InstallOutcome_Serialize>("install_file", { modId, modName, fileId, downloadUrl, fileType, modVersion, gamePath, gameId }),
	/**
	 *  Installs a mod from a local file the user dropped onto the window (Explorer drag-drop).
	 *  The file carries no modworkshop identity, so it is installed as an unidentified entry
	 *  (negative id, "unknown" version) exactly like an ambiently-discovered pak; get_installed's
	 *  SHA256 upgrade resolves its real identity on the next refresh. The dropped file is copied into
	 *  temp first so resolution/cleanup never touches the user's original.
	 */
	installDroppedFile: (path: string, gamePath: string, folderId: string | null, gameId: string) => __TAURI_INVOKE<InstallOutcome_Serialize>("install_dropped_file", { path, gamePath, folderId, gameId }),
	/**
	 *  User-initiated Tier 3 identification (see nexus_content.rs): looks up one already-
	 *  installed, unidentified mod against Nexus's content index. Never called from
	 *  get_installed — the renderer calls this per-mod from an explicit "Identify" action,
	 *  same shape as the ModWorkshop identification pipeline being automatic (SHA256) while
	 *  this one, lacking a hash to key on, cannot safely be.
	 */
	identifyModViaNexusContent: (gamePath: string, uid: string, gameId: string) => __TAURI_INVOKE<NexusContentIdentifyOutcome>("identify_mod_via_nexus_content", { gamePath, uid, gameId }),
	installFromZipEntry: (args: InstallFromZipEntryArgs) => __TAURI_INVOKE<null>("install_from_zip_entry", { args }),
	/**
	 *  Installs a Crime Boss archive whose content has no enclosing folder (every entry sits at the
	 *  zip root); the renderer reaches this after a user confirms a CB_FLAT_ARCHIVE dialog. There's
	 *  only one possible destination (the primary mods target, which blanket-accepts any directory),
	 *  so unlike install_from_zip_entry there's no entry to pick: the whole archive is extracted flat
	 *  and installed as a single mods/<name> folder named from the mod's display name.
	 */
	installCbFlatArchive: (zipPath: string, modId: number, modName: string, fileId: number, fileType: string, modVersion: string, gamePath: string, folderId: string | null) => __TAURI_INVOKE<null>("install_cb_flat_archive", { zipPath, modId, modName, fileId, fileType, modVersion, gamePath, folderId }),
	installHostPack: (args: InstallHostPackArgs) => __TAURI_INVOKE<null>("install_host_pack", { args }),
	deleteTempFile: (path: string) => __TAURI_INVOKE<void>("delete_temp_file", { path }),
	uninstallMod: (gamePath: string, uid: string, gameId: string) => __TAURI_INVOKE<null>("uninstall_mod", { gamePath, uid, gameId }),
	enableMod: (gamePath: string, uid: string, gameId: string) => __TAURI_INVOKE<null>("enable_mod", { gamePath, uid, gameId }),
	disableMod: (gamePath: string, uid: string, gameId: string) => __TAURI_INVOKE<null>("disable_mod", { gamePath, uid, gameId }),
	moveCrimebossModTarget: (gamePath: string, uid: string) => __TAURI_INVOKE<null>("move_crimeboss_mod_target", { gamePath, uid }),
	reorderInFolder: (gamePath: string, folderId: string | null, orderedUids: string[], gameId: string) => __TAURI_INVOKE<null>("reorder_in_folder", { gamePath, folderId, orderedUids, gameId }),
	moveToFolder: (gamePath: string, uid: string, targetFolderId: string | null, targetPosition: number, gameId: string) => __TAURI_INVOKE<null>("move_to_folder", { gamePath, uid, targetFolderId, targetPosition, gameId }),
	reorderChildren: (gamePath: string, parentId: string | null, items: TopLevelItem[], gameId: string) => __TAURI_INVOKE<null>("reorder_children", { gamePath, parentId, items, gameId }),
	moveFolder: (gamePath: string, folderId: string, targetParentId: string | null, gameId: string) => __TAURI_INVOKE<null>("move_folder", { gamePath, folderId, targetParentId, gameId }),
	createFolder: (gamePath: string, displayName: string, parentId: string | null, gameId: string) => __TAURI_INVOKE<ModFolder>("create_folder", { gamePath, displayName, parentId, gameId }),
	renameFolder: (gamePath: string, folderId: string, displayName: string, gameId: string) => __TAURI_INVOKE<null>("rename_folder", { gamePath, folderId, displayName, gameId }),
	deleteFolder: (gamePath: string, folderId: string, gameId: string) => __TAURI_INVOKE<null>("delete_folder", { gamePath, folderId, gameId }),
	openModsFolder: (gameId: string) => __TAURI_INVOKE<null>("open_mods_folder", { gameId }),
	listModFolders: (gameId: string) => __TAURI_INVOKE<ModFolderInfo[]>("list_mod_folders", { gameId }),
	openModFolder: (gameId: string, tag: string) => __TAURI_INVOKE<null>("open_mod_folder", { gameId, tag }),
	isPd2Diesel3: (gamePath: string) => __TAURI_INVOKE<boolean>("is_pd2_diesel3", { gamePath }),
	/**
	 *  The whole registry, for the renderer to map dependency ids to loaders without
	 *  restating the tables.
	 */
	listLoaders: () => __TAURI_INVOKE<LoaderInfo[]>("list_loaders"),
	/**
	 *  The whole registry, so the renderer can ask which sources a game offers rather than
	 *  restating the mapping.
	 */
	listSources: () => __TAURI_INVOKE<SourceInfo[]>("list_sources"),
	checkLoader: (loaderId: string, gameId: string, gamePath: string) => __TAURI_INVOKE<boolean>("check_loader", { loaderId, gameId, gamePath }),
	installLoader: (loaderId: string, gamePath: string) => __TAURI_INVOKE<null>("install_loader", { loaderId, gamePath }),
	installedLaunchers: (gameId: string) => __TAURI_INVOKE<string[]>("installed_launchers", { gameId }),
	configureGamePath: (gameId: string, gamePath: string | null) => __TAURI_INVOKE<void>("configure_game_path", { gameId, gamePath }),
	pickFolder: (defaultPath: string | null) => __TAURI_INVOKE<string | null>("pick_folder", { defaultPath }),
	launchGame: (gameId: string) => __TAURI_INVOKE<null>("launch_game", { gameId }),
	launchWithoutMods: (gameId: string) => __TAURI_INVOKE<null>("launch_without_mods", { gameId }),
	restoreMods: (gameId: string) => __TAURI_INVOKE<null>("restore_mods", { gameId }),
	isGameRunning: (gameId: string) => __TAURI_INVOKE<boolean>("is_game_running", { gameId }),
	stopGame: (gameId: string) => __TAURI_INVOKE<null>("stop_game", { gameId }),
	shellOpenExternal: (url: string) => __TAURI_INVOKE<void>("shell_open_external", { url }),
	shellOpenPath: (path: string) => __TAURI_INVOKE<void>("shell_open_path", { path }),
	openLogFile: () => __TAURI_INVOKE<void>("open_log_file"),
	openDataFolder: () => __TAURI_INVOKE<void>("open_data_folder"),
	openAppFolder: () => __TAURI_INVOKE<void>("open_app_folder"),
	checkForUpdate: () => __TAURI_INVOKE<null>("check_for_update"),
	downloadUpdate: () => __TAURI_INVOKE<null>("download_update"),
	installUpdate: () => __TAURI_INVOKE<null>("install_update"),
	/**
	 *  Caches an image and returns the cache filename for the renderer to build its
	 *  thumb:// URL from. Default: the pre-generated small variant
	 *  (thumbnail_{file}, ~10-20x smaller than the original, which can be multiple
	 *  MB), falling back to the original for old images without one
	 *  (has_thumb: false). With full = true: the original, cached under
	 *  {filename}, used by the detail page (banner, lightbox), where the CDN's
	 *  missing cache headers would otherwise cost a revalidation round-trip per view.
	 */
	getThumbnail: (filename: string, full: boolean | null) => __TAURI_INVOKE<string>("get_thumbnail", { filename, full }),
	getIndexModFiles: (modId: number, gameId: string) => __TAURI_INVOKE<IndexModFile[]>("get_index_mod_files", { modId, gameId }),
	/**
	 *  Page 1 only: the cached, TTL-backed entry point used on first
	 *  load and by the Refresh button.
	 */
	fetchNews: (gameId: string) => __TAURI_INVOKE<NewsResult>("fetch_news", { gameId }),
	refreshNews: (gameId: string) => __TAURI_INVOKE<NewsResult>("refresh_news", { gameId }),
	/**
	 *  Pages other than 1, fetched on demand, never cached (the disk cache
	 *  exists to make the default page-1 view instant, not to mirror the whole
	 *  site).
	 */
	fetchNewsPage: (gameId: string, page: number) => __TAURI_INVOKE<NewsResult>("fetch_news_page", { gameId, page }),
	getStorageUsage: () => __TAURI_INVOKE<StorageUsage>("get_storage_usage"),
	clearThumbnailCache: () => __TAURI_INVOKE<number>("clear_thumbnail_cache"),
	clearIndexCache: () => __TAURI_INVOKE<number>("clear_index_cache"),
	clearNewsCache: () => __TAURI_INVOKE<number>("clear_news_cache"),
	/**
	 *  Factory-resets settings.json to defaults: clears every configured game path,
	 *  launcher choice, launch options, analytics consent + id, and all other
	 *  preferences. Does not touch installed mods, game files, or the on-disk caches.
	 */
	resetAppSettings: () => __TAURI_INVOKE<void>("reset_app_settings"),
};

/* Types */
export type CbFlatPayload = CbFlatPayload_Serialize | CbFlatPayload_Deserialize;

export type CbFlatPayload_Deserialize = {
	zipPath: string,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

export type CbFlatPayload_Serialize = {
	zipPath: string,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

export type FilePage = {
	data: ModFile[],
	meta: PageMeta,
};

export type GameSettings = GameSettings_Serialize | GameSettings_Deserialize;

export type GameSettings_Deserialize = {
	gamePath: string | null,
	launcher: string | null,
	launchOptions?: string,
	suppressCrashReporter?: boolean,
	crimebossInstallMode?: string,
};

export type GameSettings_Serialize = {
	gamePath: string | null,
	launcher: string | null,
	launchOptions: string,
	suppressCrashReporter: boolean,
	crimebossInstallMode: string,
};

export type HostPackPayload = HostPackPayload_Serialize | HostPackPayload_Deserialize;

export type HostPackPayload_Deserialize = {
	zipPath: string,
	entries: string[],
	hostModId: number,
	hostName: string,
	hostSubpath: string,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

export type HostPackPayload_Serialize = {
	zipPath: string,
	entries: string[],
	hostModId: number,
	hostName: string,
	hostSubpath: string,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

export type IndexModFile = {
	fileRemoteId: number,
	entryName: string,
};

export type InstallFromZipEntryArgs = {
	zipPath: string,
	entryName: string,
	modId: number,
	modName: string,
	fileId: number,
	fileType: string,
	modVersion: string,
	gamePath: string,
	folderId: string | null,
	gameId: string,
	locationTag: string | null,
	entryKind: string | null,
};

/**
 *  Installs a content set from an already-downloaded archive into a host mod's folder (e.g. a
 *  Menu Backgrounds set into mods/Menu Backgrounds/Assets/). The renderer reaches this after a
 *  HOST_MOD_PACK sentinel; the zip is left in place for multi-set installs (caller deletes it).
 */
export type InstallHostPackArgs = {
	zipPath: string,
	entryName: string,
	modId: number,
	modName: string,
	fileId: number,
	fileType: string,
	modVersion: string,
	gamePath: string,
	hostModId: number,
	hostSubpath: string,
	gameId: string,
};

/**
 *  What an install command produced: a finished install, or an archive that needs a
 *  user decision first. Returned in the Ok channel so the renderer handles every case
 *  with an exhaustive switch instead of parsing sentinel strings out of errors.
 */
export type InstallOutcome = InstallOutcome_Serialize | InstallOutcome_Deserialize;

/**
 *  What an install command produced: a finished install, or an archive that needs a
 *  user decision first. Returned in the Ok channel so the renderer handles every case
 *  with an exhaustive switch instead of parsing sentinel strings out of errors.
 */
export type InstallOutcome_Deserialize = "installed" | ({ needsPicker: ZipMultiPakPayload_Deserialize }) & { needsCbFlatConfirm?: never; needsHostChoice?: never } | ({ needsHostChoice: HostPackPayload_Deserialize }) & { needsCbFlatConfirm?: never; needsPicker?: never } | ({ needsCbFlatConfirm: CbFlatPayload_Deserialize }) & { needsHostChoice?: never; needsPicker?: never } | "unrecognized";

/**
 *  What an install command produced: a finished install, or an archive that needs a
 *  user decision first. Returned in the Ok channel so the renderer handles every case
 *  with an exhaustive switch instead of parsing sentinel strings out of errors.
 */
export type InstallOutcome_Serialize = "installed" | ({ needsPicker: ZipMultiPakPayload_Serialize }) & { needsCbFlatConfirm?: never; needsHostChoice?: never } | ({ needsHostChoice: HostPackPayload_Serialize }) & { needsCbFlatConfirm?: never; needsPicker?: never } | ({ needsCbFlatConfirm: CbFlatPayload_Serialize }) & { needsHostChoice?: never; needsPicker?: never } | "unrecognized";

export type InstalledMod = InstalledMod_Serialize | InstalledMod_Deserialize;

export type InstalledMod_Deserialize = {
	uid?: string,
	id: number,
	name: string,
	version: string,
	filename: string,
	enabled: boolean,
	installedAt: string,
	source?: string,
	remoteId?: string | null,
	fileRemoteId?: string | null,
	author?: string | null,
	thumbnailUrl?: string | null,
	fileId: number | null,
	fileType: string | null,
	sha256: string | null,
	priority: number | null,
	missing: boolean | null,
	folderId?: string | null,
	archiveBroken?: boolean | null,
	location?: string | null,
	updateStatus?: UpdateStatus,
	nexusContentMissed?: boolean | null,
};

export type InstalledMod_Serialize = {
	uid: string,
	id: number,
	name: string,
	version: string,
	filename: string,
	enabled: boolean,
	installedAt: string,
	source: string,
	remoteId?: string | null,
	fileRemoteId?: string | null,
	author?: string | null,
	thumbnailUrl?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	sha256?: string | null,
	priority?: number | null,
	missing?: boolean | null,
	folderId?: string | null,
	archiveBroken?: boolean | null,
	location?: string | null,
	updateStatus?: UpdateStatus,
	nexusContentMissed?: boolean | null,
};

export type InstalledResponse = InstalledResponse_Serialize | InstalledResponse_Deserialize;

export type InstalledResponse_Deserialize = {
	mods: InstalledMod_Deserialize[],
	folders: ModFolder[],
	modsHidden: boolean,
};

export type InstalledResponse_Serialize = {
	mods: InstalledMod_Serialize[],
	folders: ModFolder[],
	modsHidden: boolean,
};

export type InstructsTemplate = {
	id: number,
	name: string,
	instructions: string,
	dependencies: ModDependency[],
};

export type LinkPage = {
	data: ModLink[],
	meta: PageMeta,
};

export type ListModsParams = {
	query: string | null,
	limit: number | null,
	sort: string | null,
	category_id: number | null,
	page: number | null,
	ids: number[] | null,
	tags: number[] | null,
	block_tags: number[] | null,
};

/**
 *  The registry as the renderer sees it, so loader ids and their games live in one
 *  place instead of being restated in deps.ts.
 */
export type LoaderInfo = {
	id: string,
	modworkshopIds: number[],
	games: string[],
	/**
	 *  No direct download - the renderer must route installs through the normal mod
	 *  flow rather than calling install_loader.
	 */
	viaModFlow: boolean,
};

/**
 *  A declared dependency. The nested mod is a SUMMARY, not a detail: modworkshop returns
 *  the listing shape here, and the renderer only ever reads summary fields off it. Typing
 *  it as a detail would also make this type recursive for no gain.
 */
export type ModDependency = {
	id: number,
	/**  None for offsite dependencies, which are hosted outside modworkshop. */
	mod_id: number | null,
	name: string | null,
	url: string | null,
	optional: boolean,
	/**  Author-defined install order. The renderer sorts by it, matching the mod page. */
	order: number | null,
	mod: ModSummary | null,
};

/**
 *  A mod as /mods/{id} returns it: every summary field plus the ones only the detail call
 *  carries. The collections are required but may be empty, which is the normalization the
 *  renderer previously did itself with `?? []` at each use.
 */
export type ModDetail = {
	id: number,
	name: string,
	desc: string,
	short_desc: string,
	version: string,
	downloads: number,
	likes: number,
	views: number,
	published_at: string,
	bumped_at: string,
	category_id: number,
	has_download: boolean,
	disable_mod_managers: boolean | null,
	thumbnail: ModThumbnail | null,
	download: ModDownload | null,
	user: ModUser,
	changelog: string | null,
	instructions: string | null,
	license: string | null,
	repo_url: string | null,
	donation: string | null,
	banner: ModImage | null,
	images: ModImage[],
	dependencies: ModDependency[],
	instructs_template: InstructsTemplate | null,
	tags: ModTag[],
	members: ModMember[],
};

/**
 *  The default download attached to a listing. modworkshop has two shapes here:
 *  file-hosted mods carry download_url/type/size, external-link mods carry only url.
 */
export type ModDownload = {
	id: number,
	version: string,
	size: number | null,
	type: string | null,
	download_url: string | null,
	url: string | null,
};

/**
 *  One downloadable file on a mod. Distinct from ModDownload above, which is the single
 *  default download a listing carries; a mod can publish many files.
 */
export type ModFile = {
	id: number,
	name: string,
	version: string,
	size: number,
	type: string | null,
	download_url: string,
	url: string | null,
	image_id: number | null,
	desc: string | null,
	label: string | null,
	downloads: number | null,
	created_at: string | null,
};

export type ModFolder = {
	id: string,
	diskName: string,
	displayName: string,
	priority: number,
	parentId: string | null,
};

export type ModFolderInfo = {
	tag: string,
	labelKey: string,
};

export type ModImage = {
	id: number,
	file: string,
	type: string,
	size: number,
	display_order: number,
	visible: boolean,
	has_thumb: boolean,
};

/**
 *  An external link a mod lists. Carries url but never download_url/type/size, which is
 *  what separates it from a hosted file.
 */
export type ModLink = {
	id: number,
	name: string,
	url: string,
	desc: string | null,
	label: string | null,
	version: string | null,
	image_id: number | null,
	downloads: number | null,
	created_at: string | null,
};

export type ModMember = {
	id: number,
	name: string,
	level: string,
	accepted: boolean,
	donation_url: string | null,
	avatar: string | null,
	avatar_has_thumb: boolean | null,
};

export type ModPage = {
	data: ModSummary[],
	meta: PageMeta,
};

/**
 *  A mod as a listing returns it. The detail call adds images, banner, dependencies,
 *  instructs_template and tags, which is why those are deliberately absent here.
 */
export type ModSummary = {
	id: number,
	name: string,
	desc: string,
	short_desc: string,
	version: string,
	downloads: number,
	likes: number,
	views: number,
	published_at: string,
	bumped_at: string,
	category_id: number,
	has_download: boolean,
	disable_mod_managers: boolean | null,
	thumbnail: ModThumbnail | null,
	download: ModDownload | null,
	user: ModUser,
};

export type ModTag = {
	id: number,
	name: string,
	color: string,
};

export type ModThumbnail = {
	file: string,
	has_thumb: boolean | null,
};

export type ModUser = {
	id: number | null,
	name: string,
	donation_url: string | null,
	avatar: string | null,
	avatar_has_thumb: boolean | null,
};

export type NewsItem = {
	title: string,
	url: string,
	date: string,
	excerpt: string,
	image: string | null,
	categories: string[],
};

export type NewsResult = {
	items: NewsItem[],
	totalPages: number,
};

/**
 *  What identifying a dropped archive against Nexus produced. Returned in the Ok
 *  channel, mirroring InstallOutcome (mods/mod.rs), so the renderer handles every
 *  case explicitly instead of guessing from an empty list.
 */
export type NexusArchiveIdentity = "notFound" | ({ identified: NexusHashMatch }) & { ambiguous?: never } | 
/**
 *  The same archive bytes are published under more than one Nexus mod (a real,
 *  observed shape — cross-posted content) and fileSize could not tell them apart
 *  because they are, by definition, the same size. The caller must ask the user.
 */
({ ambiguous: NexusHashMatch[] }) & { identified?: never };

/**  What attempting Nexus content identification for one installed mod produced. */
export type NexusContentIdentifyOutcome = 
/**
 *  Already identified, already carrying a permanent miss, or nothing queryable
 *  could be derived (no folder segment, or the file could not be found on disk) —
 *  nothing was attempted, so nothing was recorded.
 */
"skipped" | "notFound" | "ambiguous" | "identified";

export type NexusHashMatch = {
	modId: number,
	fileId: number,
	name: string,
	version: string,
	fileName: string,
	fileSize: number,
};

export type PageMeta = {
	current_page: number,
	last_page: number,
	per_page: number,
	total: number,
};

export type SourceGameInfo = {
	gameId: string,
	nativeId: string,
};

/**
 *  The registry as the renderer sees it, so the source list a game offers lives in one
 *  place instead of being derived from a per-source field on the game spec.
 */
export type SourceInfo = {
	id: string,
	/**
	 *  Games this source serves, paired with the id it knows each by. The renderer needs
	 *  the native id to build links (a Nexus mod page URL is keyed by domain slug).
	 */
	games: SourceGameInfo[],
};

export type StartupPhase = "prepare" | "interface" | "game" | "mods" | "ready" | "error";

/**
 *  Sizes in bytes of the app's regenerable on-disk caches, for the Settings
 *  storage view. settings.json (user data) and the renderer's localStorage
 *  mod-metadata cache are measured and cleared elsewhere.
 */
export type StorageUsage = {
	thumbnails: number,
	indexDb: number,
	news: number,
};

export type TopLevelItem = { type: "folder"; id: string } | { type: "mod"; id: string };

/**
 *  Whether a mod's installed version can be compared against the remote one.
 * 
 *  This used to live in the version STRING, with "unknown" and "outdated" standing in for
 *  a real value. That worked only because neither is a plausible modworkshop version, and
 *  it forced every reader to know both sentinels. Per-source version semantics do not fit
 *  one overloaded string either: Nexus search returns no version at all, and Steam
 *  Workshop has update timestamps rather than versions.
 */
export type UpdateStatus = 
/**  version holds a real, comparable value. */
"known" | 
/**
 *  No comparable version: an unidentified mod, or an embedded-id mod that declares
 *  none. Never surfaces an update, since it would nag forever with nothing to compare.
 */
"unknown" | 
/**
 *  Confirmed stale: a name match succeeded AFTER a SHA256 check against the index's
 *  current file had already failed, so the installed bytes are known to differ.
 */
"outdated";

/**
 *  Archive shapes that need a user decision before installing. Each variant carries the
 *  payload its renderer modal renders from; the mod-context fields (mod_id, mod_name, ...)
 *  are None here and filled by the install command via with_mod_context, since only the
 *  command knows which mod the archive belongs to.
 */
export type ZipMultiPakPayload = ZipMultiPakPayload_Serialize | ZipMultiPakPayload_Deserialize;

/**
 *  Archive shapes that need a user decision before installing. Each variant carries the
 *  payload its renderer modal renders from; the mod-context fields (mod_id, mod_name, ...)
 *  are None here and filled by the install command via with_mod_context, since only the
 *  command knows which mod the archive belongs to.
 */
export type ZipMultiPakPayload_Deserialize = {
	zipPath: string,
	entries: string[],
	targetTag: string | null,
	entryTags?: (string | null)[] | null,
	entryKind?: string | null,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

/**
 *  Archive shapes that need a user decision before installing. Each variant carries the
 *  payload its renderer modal renders from; the mod-context fields (mod_id, mod_name, ...)
 *  are None here and filled by the install command via with_mod_context, since only the
 *  command knows which mod the archive belongs to.
 */
export type ZipMultiPakPayload_Serialize = {
	zipPath: string,
	entries: string[],
	targetTag: string | null,
	entryTags?: (string | null)[] | null,
	entryKind?: string | null,
	modId?: number | null,
	modName?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	modVersion?: string | null,
};

